[font]
size = 14.0

[font.bold]
family = "MesloLGM Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font Propo"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font Propo"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window.dimensions]
columns = 215
lines = 36

[window.position]
x = 5
y = 57
